apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-order-backend
spec:
  selector:
    matchLabels:
      app: drone-order-backend
  template:
    metadata:
      labels:
        app: drone-order-backend
    spec:
      containers:
        - name: drone-order-backend
          image: 555516925462.dkr.ecr.ap-east-1.amazonaws.com/drone-order-backend:latest
          ports:
              - containerPort: 8080
          resources:
            limits:
              cpu: 700m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: drone-order-backend
spec:
  selector:
    app: drone-order-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/success-codes: 200-499
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: drone-order-backend
                port:
                  number: 8080
